---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ephemeron.manager.fullname" . }}-hook-token
  labels:
    {{- include "ephemeron.manager.labels" . | nindent 4 }}
stringData:
  hookToken: {{ .Values.registry.hookToken | default "change-me" | quote }}
