---
apiVersion: v2
name: ephemeron
description: Self-hosted ephemeral container registry
type: application
version: 0.0.1
appVersion: latest

dependencies:
  - name: redis-ha
    version: 6.4.3
    repository: oci://ghcr.io/tamcore/charts
